### ISSUE TITLE
API Endpoint

### ISSUE THREAD

**Issue by webhead2oo9** [ItzCrazyKns/Perplexica#141] opened 2024-05-24 23:11 UTC
**Is your feature request related to a problem? Please describe.**
Request for API Endpoint for calling this as a local search provider.

**Describe the solution you'd like**
I'm looking for a curl based possibly endpoint off the existing search, an example would be with an json output such as 

{
  "status": "complete",
  "results": [
    {
      "body": "Raw output",
      "sources": "Comma separated sources with numbers"
    }
  ],
  "sources": [
    {
      "source": "1",
      "url": "URLHere"
    }
  ]
}

**Describe alternatives you've considered**
I don't know if the sources need to be broken down in detail in a separate list, was an initial thought however. 
I think any open standard the data can be retrieved would be useful, but I do believe a status response is needed, as well as the text and sources, even if individual sources are not provided in the raw text.

**Comment by NisugaJ** [comment] 2024-05-25 23:33
This would be a nice addition.

**Comment by quantumalchemy** [comment] 2024-06-19 13:27
+1  great for integration into ai agent apps

**Comment by ItzCrazyKns** [comment] 2024-06-29 10:16
Hi everyone, I am looking into this right now. Lets see what can be done over here.

**Comment by ksingh-scogo** [comment] 2024-07-12 19:53
> Hi everyone, I am looking into this right now. Lets see what can be done over here.

Hey @ItzCrazyKns excellent work with Perplexica 

I can see that you have closed this issue, if this task is completed , can you guide on how to use perplexica over APIs , looking for example

**Comment by ItzCrazyKns** [comment] 2024-07-13 04:17
> > Hi everyone, I am looking into this right now. Lets see what can be done over here.
> 
> Hey @ItzCrazyKns excellent work with Perplexica
> 
> I can see that you have closed this issue, if this task is completed , can you guide on how to use perplexica over APIs , looking for example

The issue is still open.

**Comment by ksingh-scogo** [comment] 2024-07-13 08:56
Thanks @ItzCrazyKns  

Tracking this , happy to be a tester once this arrives

**Comment by martinzhangdidi** [comment] 2024-07-13 21:06
its important

**Comment by Jiuzhouh** [comment] 2024-07-16 05:08
hope this could be done ASAP.

**Comment by sombandy** [comment] 2024-07-24 17:58
I recently tried Perplexica and was impressed with its web research capabilities. However, API access is essential for us to integrate this in our automated workflows. We would greatly appreciate having this as soon as possible.

Also, I'm assuming that the current design uses some backend API to fetch search results, even if it's not publicly documented. Is there a way to directly access this API, even if it's not well formatted? Thanks

**Comment by Aboodseada1** [comment] 2024-07-25 11:04
Hello,
I tried this tool 2 days ago, and was hoping to find any API for it, and I didn't, so I created a selenium automation that automates the process of sending queries and getting responses back to validate my Excel sheet list :D thank you for this amazing tool and I really hope there will be API available soon :D

![image](https://github.com/user-attachments/assets/8b474331-0699-4634-8c6a-c4bf2129f7b7)

**Comment by ItzCrazyKns** [comment] 2024-07-25 14:23
Oh my god, people are finding their own way. I'll try to release the API before the discover feature.

**Comment by RazeBerry** [comment] 2024-07-25 19:38
@ItzCrazyKns it would be also quite helpful, and I understand there is a lot on your plate right now, to have the API calls have multiple-threads rather than having a single one occupied all the time since a single call does take several seconds at least.

**Comment by ItzCrazyKns** [comment] 2024-07-26 15:19
Yes, ofcourse

**Comment by jacepark12** [comment] 2024-07-29 14:46
Also waiting for the API release! 
In the meantime, I am using a simple Python script to call the search API(WS) as python function. 
For anyone looking for a API or a way to integrate with other tools before the official release, I think this script could be a good start.

https://gist.github.com/jacepark12/1886f6e95d9051f198992323758defa1

**Comment by FC-FUZ** [comment] 2024-08-06 21:12
> Oh my god, people are finding their own way. I'll try to release the API before the discover feature.

Is it possible to receive citations back with search results with the API?

**Comment by patrickrho** [comment] 2024-08-17 00:54
We need the endpoint like how Perplexity provides oai compatible endpoint.

**Comment by nkeilar** [comment] 2024-08-20 08:26
Is this a complex thing to tackle? I've made an AI assistant that uses perplexity api and would love to be able to leverage this in our stack instead. Great idea! Kudos!

**Comment by P4ulchen** [comment] 2024-08-28 17:15
+1

**Comment by ChieF-TroN** [comment] 2024-09-09 16:35
Would love to have this officially support. Trying to implement this into my toolset as we speak :)

**Comment by DenisMarasescu** [comment] 2024-09-14 17:51
+1

**Comment by npnpatidar** [comment] 2024-09-19 12:31
+1

**Comment by whogben** [comment] 2024-09-19 16:08
+1

my recommendation would be to match the Perplexity API, which is really just one endpoint that starts as a subset of the OpenAI ChatCompletions endpoint - that would make it a drop-in replacement for tons of software out there with no coding required.

The minimum subset of the API would be:
- POST to an endpoint including `"messages": [ {"role": "system/user/assistant", "content":"text or jsonstring"}]`
- receive a response including `"choices": [{"message": {"role":assistant, "content": "text or jsonstring"}]` or `"error": "some string"`

https://docs.perplexity.ai/api-reference/chat-completions

**Comment by tuhinmallick** [comment] 2024-10-06 19:33
Waiting patiently for the api. Good work on the project though.

**Comment by ItzCrazyKns** [comment] 2024-10-09 04:58
The API has been released quite a while a ago: https://github.com/ItzCrazyKns/Perplexica?tab=readme-ov-file#using-perplexicas-api

**Closed by ItzCrazyKns** 2024-10-09 04:58 UTC
Labels: enhancement
