### ISSUE TITLE
There is no ollama model selection in settings, how can I find it?

### ISSUE THREAD

**Issue by liujvnes** [ItzCrazyKns/Perplexica#54] opened 2024-05-03 13:52 UTC
There is no ollama model selection in settings, how can I find it?

![image](https://github.com/ItzCrazyKns/Perplexica/assets/25132014/7b4f850e-f7d4-433f-aa57-c5c2048cdd43)

**Comment by ItzCrazyKns** [comment] 2024-05-03 14:08
Open up the developer settings menu, go to application then localStorage and delete all values. Refresh your page and it should be fixed. If not share logs from the backend and the browser's console

**Comment by liujvnes** [comment] 2024-05-03 14:18
I can't find the developer settings menu, please help me, what should I do!

**Comment by ItzCrazyKns** [comment] 2024-05-03 14:23
On windows: press ctrl + Option + J
Mac os: Cmd + Option + J

**Comment by ItzCrazyKns** [comment] 2024-05-05 12:03
Hi, if you still face this error please update to the latest version. The issue is fixed. If you face the error again, feel free to re-open the issue

**Closed by ItzCrazyKns** 2024-05-05 12:03 UTC
