### ISSUE TITLE
Unable to load a ollama model

### ISSUE THREAD

**Issue by jatindahiya027** [ItzCrazyKns/Perplexica#56] opened 2024-05-03 20:36 UTC
I installed Perplexica on my windows pc. ollama is working fine when using from the terminal but in perplexica I get invalid provider in chat model dropdown.

![Screenshot 2024-05-04 020249](https://github.com/ItzCrazyKns/Perplexica/assets/74525731/c6fa9958-5f0e-4450-9881-05371363411a)

**Comment by ItzCrazyKns** [comment] 2024-05-04 03:38
Can you show the logs from the backend

**Comment by joseph6377** [comment] 2024-05-04 04:40
I am also facing same issue on mac .

perplexica-backend-1   | yarn run v1.22.19
perplexica-backend-1   | $ node dist/app.js
searxng-1              | SIGINT/SIGTERM received...killing workers...
searxng-1              | worker 1 buried after 1 seconds
searxng-1              | worker 2 buried after 1 seconds
searxng-1              | worker 3 buried after 1 seconds
searxng-1              | worker 4 buried after 1 seconds
searxng-1              | worker 5 buried after 1 seconds
searxng-1              | worker 6 buried after 1 seconds
searxng-1              | worker 7 buried after 1 seconds
searxng-1              | worker 8 buried after 1 seconds
searxng-1              | goodbye to uWSGI.
searxng-1              | SearXNG version 2024.4.30+c8d0b6529
searxng-1              | Use existing /etc/searxng/uwsgi.ini
searxng-1              | Use existing /etc/searxng/settings.yml
searxng-1              | Listen on 0.0.0.0:8080
searxng-1              | [uWSGI] getting INI configuration from /etc/searxng/uwsgi.ini
searxng-1              | [uwsgi-static] added mapping for /static => /usr/local/searxng/searx/static
searxng-1              | *** Starting uWSGI 2.0.23 (64bit) on [Sat May  4 04:40:09 2024] ***
searxng-1              | compiled with version: 13.2.1 20231014 on 30 November 2023 14:34:33
searxng-1              | os: Linux-6.6.22-linuxkit #1 SMP Fri Mar 29 12:21:27 UTC 2024
searxng-1              | nodename: ef86d4112e12
searxng-1              | machine: aarch64
searxng-1              | clock source: unix
searxng-1              | pcre jit disabled
searxng-1              | detected number of CPU cores: 8
searxng-1              | current working directory: /usr/local/searxng
searxng-1              | detected binary path: /usr/sbin/uwsgi
searxng-1              | chdir() to /usr/local/searxng/searx/
searxng-1              | your memory page size is 4096 bytes
searxng-1              | detected max file descriptor number: 1048576
searxng-1              | building mime-types dictionary from file /etc/mime.types...1390 entry found
searxng-1              | lock engine: pthread robust mutexes
searxng-1              | thunder lock: disabled (you can enable it with --thunder-lock)
searxng-1              | uwsgi socket 0 bound to TCP address 0.0.0.0:8080 fd 3
searxng-1              | Python version: 3.11.9 (main, Apr 14 2024, 13:40:00) [GCC 13.2.1 20231014]
searxng-1              | Python main interpreter initialized at 0xffffb2ed0ac0
searxng-1              | python threads support enabled
searxng-1              | your server socket listen backlog is limited to 100 connections
searxng-1              | your mercy for graceful operations on workers is 60 seconds
searxng-1              | mapped 1086048 bytes (1060 KB) for 32 cores
searxng-1              | *** Operational MODE: preforking+threaded ***
searxng-1              | added /usr/local/searxng/ to pythonpath.
searxng-1              | spawned uWSGI master process (pid: 7)
searxng-1              | spawned uWSGI worker 1 (pid: 10, cores: 4)
searxng-1              | spawned uWSGI worker 2 (pid: 11, cores: 4)
searxng-1              | spawned 4 offload threads for uWSGI worker 1
searxng-1              | spawned uWSGI worker 3 (pid: 16, cores: 4)
searxng-1              | spawned uWSGI worker 4 (pid: 17, cores: 4)
searxng-1              | spawned uWSGI worker 5 (pid: 18, cores: 4)
searxng-1              | spawned uWSGI worker 6 (pid: 22, cores: 4)
searxng-1              | spawned 4 offload threads for uWSGI worker 3
searxng-1              | spawned 4 offload threads for uWSGI worker 2
searxng-1              | spawned uWSGI worker 7 (pid: 28, cores: 4)
searxng-1              | spawned uWSGI worker 8 (pid: 29, cores: 4)
searxng-1              | spawned 4 offload threads for uWSGI worker 7
searxng-1              | spawned 4 offload threads for uWSGI worker 4
searxng-1              | spawned 4 offload threads for uWSGI worker 8
searxng-1              | spawned 4 offload threads for uWSGI worker 5
searxng-1              | spawned 4 offload threads for uWSGI worker 6
perplexica-frontend-1  | yarn run v1.22.19
perplexica-frontend-1  | $ next start
searxng-1              | 2024-05-04 04:40:10,041 WARNING:searx.botdetection.config: missing config file: /etc/searxng/limiter.toml
searxng-1              | WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xffffb2ed0ac0 pid: 16 (default app)
searxng-1              | 2024-05-04 04:40:10,200 WARNING:searx.botdetection.config: missing config file: /etc/searxng/limiter.toml
searxng-1              | WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xffffb2ed0ac0 pid: 29 (default app)
searxng-1              | 2024-05-04 04:40:10,243 WARNING:searx.botdetection.config: missing config file: /etc/searxng/limiter.toml
searxng-1              | WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xffffb2ed0ac0 pid: 11 (default app)
searxng-1              | 2024-05-04 04:40:10,260 WARNING:searx.botdetection.config: missing config file: /etc/searxng/limiter.toml
searxng-1              | WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xffffb2ed0ac0 pid: 17 (default app)
perplexica-backend-1   | info: WebSocket server started on port 3001
perplexica-backend-1   | (node:27) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
perplexica-backend-1   | (Use `node --trace-deprecation ...` to show where the warning was created)
perplexica-backend-1   | info: Server is running on port 3001
searxng-1              | 2024-05-04 04:40:10,284 WARNING:searx.botdetection.config: missing config file: /etc/searxng/limiter.toml
searxng-1              | WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xffffb2ed0ac0 pid: 10 (default app)
searxng-1              | 2024-05-04 04:40:10,303 WARNING:searx.botdetection.config: missing config file: /etc/searxng/limiter.toml
searxng-1              | WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xffffb2ed0ac0 pid: 18 (default app)
perplexica-frontend-1  |    ▲ Next.js 14.1.4
perplexica-frontend-1  |    - Local:        http://localhost:3000
perplexica-frontend-1  | 
searxng-1              | 2024-05-04 04:40:10,326 WARNING:searx.botdetection.config: missing config file: /etc/searxng/limiter.toml
searxng-1              | WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xffffb2ed0ac0 pid: 28 (default app)
searxng-1              | 2024-05-04 04:40:10,360 WARNING:searx.botdetection.config: missing config file: /etc/searxng/limiter.toml
searxng-1              | WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xffffb2ed0ac0 pid: 22 (default app)
perplexica-frontend-1  |  ✓ Ready in 327ms

**Comment by delfireinoso** [comment] 2024-05-04 08:43
The same problem here on a M2 Mac. Version 1.00 has a parameter to select Ollama and a model in the config file
When you had Perplexica running you could change the model.

From Perplexica 1.1 the model it's not defined  and Perplexica is unable to get the model list directly from Ollama. And we have changed all ways to coneect Ollama defined on the congig file without luck.

Another think that it's related: Perpelxica doesn't connect wel with searxng, it takes a lot of time to pull a search result, but searxng on port 4000 is fast. I thing all is a problem of communication between services

**Comment by TheWood1978** [comment] 2024-05-04 10:43
Fresh install, same issue here cant choose a Ollama model.

**Comment by yuisheaven** [comment] 2024-05-04 14:36
Fresh docker install here as well, but on my side it does neither load the chat, nor embedding model from ollama even though I have llama 3 and nomic embed available from within ollama directly.

Logs:
perplexica-backend-1   | error: Error loading Ollama models: TypeError: fetch failed
                    perplexica-backend-1   | error: Error loading Ollama embeddings: TypeError: fetch failed
                    perplexica-backend-1   | error: Error loading Ollama models: TypeError: fetch failed
                    perplexica-backend-1   | error: Error loading Ollama embeddings: TypeError: fetch failed

**Comment by delfireinoso** [comment] 2024-05-04 15:18
Installed on another computer, fresh install of docker, Ollama running and nothing comes

**Comment by yuisheaven** [comment] 2024-05-04 15:33
> Installed on another computer, fresh install of docker, Ollama running and nothing comes

On Windows, or on what exactly? Did you change any of the settings except for the ollama url?

**Comment by delfireinoso** [comment] 2024-05-04 15:38
On an Intel MacPro

**Comment by delfireinoso** [comment] 2024-05-04 18:18
Please, Perpelxica it's a great idea.  Running perfectly would be more than a great idea. I love Docker because a container can take care of all dependencies and run smoothly. So please through Compose or as a Docker Image, the work is better in his container. More  when a lot of things are integrated. Now my thoughts: OpenHui pulls the list of models from Ollama, and it goes to http://host.docker.internal:11434 on windows, linux and MacOS. So this should work.

**Comment by mikes-bowden** [comment] 2024-05-05 03:22
> Fresh docker install from master branch here. On my side it does neither load the chat, nor embedding model from ollama even though I have llama 3 and nomic embed available from within ollama directly.
> 
> Logs: perplexica-backend-1 | error: Error loading Ollama models: TypeError: fetch failed perplexica-backend-1 | error: Error loading Ollama embeddings: TypeError: fetch failed perplexica-backend-1 | error: Error loading Ollama models: TypeError: fetch failed perplexica-backend-1 | error: Error loading Ollama embeddings: TypeError: fetch failed

I got it to show by adding OpenAI and setting it for embedding, saving, and refreshing. It gave the same error while trying to use OpenAI for embedding. Once I did that, I swapped back to Ollama, and it pulled my models to select an embedding model. I am also able to use OpenAI embedding models as well. Not sure what's causing that. Hopefully that helps.

**Comment by yuisheaven** [comment] 2024-05-05 03:48
> > Fresh docker install from master branch here. On my side it does neither load the chat, nor embedding model from ollama even though I have llama 3 and nomic embed available from within ollama directly.
> > Logs: perplexica-backend-1 | error: Error loading Ollama models: TypeError: fetch failed perplexica-backend-1 | error: Error loading Ollama embeddings: TypeError: fetch failed perplexica-backend-1 | error: Error loading Ollama models: TypeError: fetch failed perplexica-backend-1 | error: Error loading Ollama embeddings: TypeError: fetch failed
> 
> I got it to show by adding OpenAI and setting it for embedding, saving, and refreshing. It gave the same error while trying to use OpenAI for embedding. Once I did that, I swapped back to Ollama, and it pulled my models to select an embedding model. I am also able to use OpenAI embedding models as well. Not sure what's causing that. Hopefully that helps.

Hey, thank you so much for sharing your solution! Indeed I got it to work like that

**Comment by ItzCrazyKns** [comment] 2024-05-05 08:34
Hi everyone, I am working on a new Docker compose file only for Ollama users that would eventually fix the issue.

**Comment by ItzCrazyKns** [comment] 2024-05-05 11:59
Hi for anyone facing this: It is resolved in version 1.3.2 (the latest release). If you still face an error feel free to re-open this issue.

**Closed by ItzCrazyKns** 2024-05-05 11:59 UTC

**Comment by jontstaz** [comment] 2024-05-13 03:31
I'm still facing this exact error in 1.3.2 so it doesn't seem to be fixed.
```
perplexica-backend-1   | error: Error loading Ollama models: TypeError: fetch failed
perplexica-backend-1   | error: Error loading Ollama embeddings: TypeError: fetch failed
```

**Comment by jmthackett** [comment] 2024-05-25 18:41
1.5.0 yields much the same on a fresh install, no API keys for OpenAI etc:

```
[perplexica-backend]  | error: Error loading Ollama models: TypeError: fetch failed
[perplexica-backend]  | error: Error loading Ollama embeddings: TypeError: fetch failed
```

**Comment by braindotai** [comment] 2024-06-13 17:57
same issue here, issue still persists, I've tried v1.3.2 as well but no luck

**Comment by RafaAguilar** [comment] 2024-06-26 07:13
For people running Ollama outside docker (like using its app), the issue is that "localhost" from within the Perplexica container is different that the "localhost" is your Ollama running with. 

Unfortunately you need to expose your Ollama to the network, as it says in the ReadMe, and then use your local network IP as the Ollama address. 

Maybe adding a proxy to the docker compose would automate this.
