### ISSUE TITLE
Settings page on mobile

### ISSUE THREAD

**Issue by ProjectMoon** [ItzCrazyKns/Perplexica#162] opened 2024-06-02 19:58 UTC
**Describe the bug**
The settings page button is not visible on the mobile UI. Or is it? Am I blind?

**To Reproduce**

1. Load Perplexica on a mobile UI (or mobile-sized screen on a desktop/laptop)

**Expected behavior**
There should be a way to access the settings menu on mobile.

**Screenshots**

**Additional context**
I cannot find the settings button. Am I just dumb? Or is it actually not there?

**Comment by WanQuanXie** [comment] 2024-06-08 09:21
This feature is still in WIP.

**Comment by ProjectMoon** [comment] 2024-06-14 13:52
I'm not even sure it's alphabetical. It seems to be the model most recently added to ollama. My guess is that it's just using the first item in the list, which is just in whatever order ollama returns from its API.

It would be very very good to have server-side settings that persist, yes.

**Comment by manjaroblack** [comment] 2024-07-05 14:41
Workaround:
On iPhone using Safari: The settings button is visible if you zoom out to 75% and view the page in landscape.

**Comment by mtcl** [comment] 2024-08-10 08:11
I do not think this issue is resolved. I still have no way to set this on mobile. Would be nice to see settings on the phone. I cannot set embedding model and llama3.1 and hence the ui fails.

**Comment by edge-sky** [comment] 2024-10-23 05:13
I am using custom openai api but config file can't not set a default key and base_url, that is mean I need to open setting and set those when a new brower. Display in phone is still can't see the button, is it have any solution?

**Comment by Passerby1011** [comment] 2024-10-29 13:25
It's been exactly five months, and compared to five months ago, none of the issues have been resolved, or perhaps the author has already abandoned this project.

**Comment by delfireinoso** [comment] 2024-10-29 13:31
The project is not abonded, the main goal was a in site use, and some UI porblems are on the remote side, not intended on the main project. It will be fixed, but it's not the main theme

**Comment by ItzCrazyKns** [comment] 2024-10-30 05:01
Added in the last few commits.

**Comment by Krzysi3k** [comment] 2024-10-30 18:37
I can't see any changes on mobile, I've tried multiple browsers and still settings button is not there, my phone is 6.7 inch screen and native resolution is 2400x1080

**Comment by delfireinoso** [comment] 2024-10-30 20:45
Until next version there are no change s, this is the meaning of the stage ment, Not now

**Comment by ItzCrazyKns** [comment] 2024-10-31 03:29
> I can't see any changes on mobile, I've tried multiple browsers and still settings button is not there, my phone is 6.7 inch screen and native resolution is 2400x1080

Follow the [update guide](https://github.com/ItzCrazyKns/Perplexica/blob/master/docs/installation/UPDATING.md)

**Comment by Krzysi3k** [comment] 2024-10-31 12:07
of course I pulled changes from repository and rebuilt containers but nothing has changed.
![Screenshot_2024-10-31-13-03-55-973_com sonelli juicessh-edit](https://github.com/user-attachments/assets/aa4099a7-5087-4ea0-b13f-acc36d4ec529)
![Screenshot_2024-10-31-13-04-54-543_mark via gp](https://github.com/user-attachments/assets/08548f94-d77b-493e-83a0-b45487b8d2d4)

**Comment by ItzCrazyKns** [comment] 2024-10-31 17:35
A bit weird, what browser are you using? I am not able to replicate with the same exact resolution.

**Comment by eliranwong** [comment] 2024-10-31 22:03
Is it possible for you simply add like http://[Perplexica_host]/settings for uses to launch the settings page?

**Comment by Krzysi3k** [comment] 2024-10-31 22:37
> A bit weird, what browser are you using? I am not able to replicate with the same exact resolution.

I have tested on brave, duckduckgo, and soul browser, they are not very popular but this is what I'm using on mobile.

**Comment by ItzCrazyKns** [comment] 2024-11-01 04:31
> Is it possible for you simply add like http://[Perplexica_host]/settings for uses to launch the settings page?

Its not a page, its a dialog that can only be opened by a button, I could make a page for it but that doesn't make any sense unless its a page.

**Comment by ItzCrazyKns** [comment] 2024-11-01 04:36
> > A bit weird, what browser are you using? I am not able to replicate with the same exact resolution.
> 
> I have tested on brave, duckduckgo, and soul browser, they are not very popular but this is what I'm using on mobile.

Could be an issue related to browser, can you try on some common browsers like Chrome?

**Comment by Krzysi3k** [comment] 2024-11-01 23:15
I can confirm that settings button is available on mobile, It was problem on my side, somehow I was still using old docker image cached on my local machine. removed old image and pulled again, now it works.
![IMG_20241102_001419](https://github.com/user-attachments/assets/9c62ff3a-36e7-4f0a-bf2c-17b6b249233a)

**Comment by edge-sky** [comment] 2024-11-12 05:51
> I can confirm that settings button is available on mobile, It was problem on my side, somehow I was still using old docker image cached on my local machine. removed old image and pulled again, now it works. ![IMG_20241102_001419](https://private-user-images.githubusercontent.com/30111578/382424252-9c62ff3a-36e7-4f0a-bf2c-17b6b249233a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzODg4MjgsIm5iZiI6MTczMTM4ODUyOCwicGF0aCI6Ii8zMDExMTU3OC8zODI0MjQyNTItOWM2MmZmM2EtMzZlNy00ZjBhLWJmMmMtMTdiNmIyNDkyMzNhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDA1MTUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjOTMxMzBkMWFiOTkzNDQ5MGUyZGIxNDk0YzllZmQ0YmRjM2NiODY1MjI3YWRhNGY4MjgwOTA1N2JjNjhiMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vd-oBkUQSLfHwImfbXdpTu5zN8s_PVFoi7kTDZhcqsw)

I have cloned the latest version, but in mobile view still can not see the setting button. I am try to clear docker an pull again, but it doesn't work too.
![image](https://github.com/user-attachments/assets/9f8f80be-e3f8-4504-89f3-2514c95e1fe9)

**Comment by edge-sky** [comment] 2024-11-12 08:26
> > I can confirm that settings button is available on mobile, It was problem on my side, somehow I was still using old docker image cached on my local machine. removed old image and pulled again, now it works. ![IMG_20241102_001419](https://private-user-images.githubusercontent.com/30111578/382424252-9c62ff3a-36e7-4f0a-bf2c-17b6b249233a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzODg4MjgsIm5iZiI6MTczMTM4ODUyOCwicGF0aCI6Ii8zMDExMTU3OC8zODI0MjQyNTItOWM2MmZmM2EtMzZlNy00ZjBhLWJmMmMtMTdiNmIyNDkyMzNhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDA1MTUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjOTMxMzBkMWFiOTkzNDQ5MGUyZGIxNDk0YzllZmQ0YmRjM2NiODY1MjI3YWRhNGY4MjgwOTA1N2JjNjhiMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vd-oBkUQSLfHwImfbXdpTu5zN8s_PVFoi7kTDZhcqsw)
> 
> I have cloned the latest version, but in mobile view still can not see the setting button. I am try to clear docker an pull again, but it doesn't work too. ![image](https://private-user-images.githubusercontent.com/95955401/385156873-c52dd730-9e1a-4ac5-8d00-317aa54506e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzOTk5MDksIm5iZiI6MTczMTM5OTYwOSwicGF0aCI6Ii85NTk1NTQwMS8zODUxNTY4NzMtYzUyZGQ3MzAtOWUxYS00YWM1LThkMDAtMzE3YWE1NDUwNmUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDA4MjAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlNTE2MWExZDRlYzY4ZmJmZTZmZjAyOTEyMWE5NTdhYjllNzY1NzIyMTUwYjM0YjgzZGVhNjNhODY1ZmQ2NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EWTTApp5hije7bctPL4EFRek7devFc7y5y6YAsEHpb8)

Actually, it is work when you set the llm config, but for custom API user who not set any config such as openai API or Ollama API, you can't open the dialog on mobile.

**Comment by mtcl** [comment] 2024-11-12 09:10
This issue is resolved now. Run below command to update.
git pull
docker compose up --build 
![Screenshot_20241112_143715_Samsung Internet](https://github.com/user-attachments/assets/dab2ba42-4a38-4d96-9314-aeca979dd2a6)

**Comment by delfireinoso** [comment] 2024-11-13 11:53
Great! works on my iPhone too!

**Closed** 2024-11-22 08:39 UTC
Labels: bug
