### ISSUE TITLE
[bug] Application error: a client-side exception has occurred

### ISSUE THREAD

**Issue by juancarlosm** [ItzCrazyKns/Perplexica#355] opened 2024-09-07 07:52 UTC
**Describe the bug**
UI hangs with: Application error: a client-side exception has occurred

**To Reproduce**
Ask: "Show me a code snippet of a website's sticky header in CSS and JavaScript."
Model: OpenAI.gpt-4o-mini

**Expected behavior**
Formatted response

**Screenshots**
![image](https://github.com/user-attachments/assets/c27a9f67-5b1a-4823-b1ba-50884523c577)

**Console log**

TypeError: Cannot read properties of undefined (reading 'type')
    at 307-7bbaef59fbef2173.js:133:6098
    at e (307-7bbaef59fbef2173.js:133:6374)
    at render (307-7bbaef59fbef2173.js:133:2889)
    at 307-7bbaef59fbef2173.js:133:6142
    at e (307-7bbaef59fbef2173.js:133:6374)
    at e (307-7bbaef59fbef2173.js:133:6273)
    at render (307-7bbaef59fbef2173.js:133:3949)
    at 307-7bbaef59fbef2173.js:133:6142
    at e (307-7bbaef59fbef2173.js:133:6374)
    at e (307-7bbaef59fbef2173.js:133:6273)
window.console.error @ 69-9a0f3fb9a2c5697d.js:1
lE @ fd9d1056-dfcb53b47a6849ce.js:1
n.callback @ fd9d1056-dfcb53b47a6849ce.js:1
ng @ fd9d1056-dfcb53b47a6849ce.js:1
ny @ fd9d1056-dfcb53b47a6849ce.js:1
a$ @ fd9d1056-dfcb53b47a6849ce.js:1
aV @ fd9d1056-dfcb53b47a6849ce.js:1
a2 @ fd9d1056-dfcb53b47a6849ce.js:1
aV @ fd9d1056-dfcb53b47a6849ce.js:1
a2 @ fd9d1056-dfcb53b47a6849ce.js:1
aV @ fd9d1056-dfcb53b47a6849ce.js:1
a2 @ fd9d1056-dfcb53b47a6849ce.js:1
aV @ fd9d1056-dfcb53b47a6849ce.js:1
a2 @ fd9d1056-dfcb53b47a6849ce.js:1
aV @ fd9d1056-dfcb53b47a6849ce.js:1
a2 @ fd9d1056-dfcb53b47a6849ce.js:1
aV @ fd9d1056-dfcb53b47a6849ce.js:1
a2 @ fd9d1056-dfcb53b47a6849ce.js:1
aV @ fd9d1056-dfcb53b47a6849ce.js:1
a2 @ fd9d1056-dfcb53b47a6849ce.js:1
aV @ fd9d1056-dfcb53b47a6849ce.js:1
a2 @ fd9d1056-dfcb53b47a6849ce.js:1
aV @ fd9d1056-dfcb53b47a6849ce.js:1
a2 @ fd9d1056-dfcb53b47a6849ce.js:1
aV @ fd9d1056-dfcb53b47a6849ce.js:1
(anonymous) @ fd9d1056-dfcb53b47a6849ce.js:1
o7 @ fd9d1056-dfcb53b47a6849ce.js:1
oH @ fd9d1056-dfcb53b47a6849ce.js:1
oj @ fd9d1056-dfcb53b47a6849ce.js:1
M @ 69-9a0f3fb9a2c5697d.js:1
69-9a0f3fb9a2c5697d.js:1 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at aY (http://localhost:3000/_next/static/chunks/fd9d1056-dfcb53b47a6849ce.js:1:76259)
    at aK (http://localhost:3000/_next/static/chunks/fd9d1056-dfcb53b47a6849ce.js:1:75683)
    at aY (http://localhost:3000/_next/static/chunks/fd9d1056-dfcb53b47a6849ce.js:1:76772)
    at aK (http://localhost:3000/_next/static/chunks/fd9d1056-dfcb53b47a6849ce.js:1:75683)
    at aY (http://localhost:3000/_next/static/chunks/fd9d1056-dfcb53b47a6849ce.js:1:76996)
    at aK (http://localhost:3000/_next/static/chunks/fd9d1056-dfcb53b47a6849ce.js:1:75683)
    at aY (http://localhost:3000/_next/static/chunks/fd9d1056-dfcb53b47a6849ce.js:1:76996)
    at aK (http://localhost:3000/_next/static/chunks/fd9d1056-dfcb53b47a6849ce.js:1:75683)
    at aY (http://localhost:3000/_next/static/chunks/fd9d1056-dfcb53b47a6849ce.js:1:76772)
    at aK (http://localhost:3000/_next/static/chunks/fd9d1056-dfcb53b47a6849ce.js:1:75683)
window.console.error @ 69-9a0f3fb9a2c5697d.js:1
lE @ fd9d1056-dfcb53b47a6849ce.js:1
n.callback @ fd9d1056-dfcb53b47a6849ce.js:1
ng @ fd9d1056-dfcb53b47a6849ce.js:1
ny @ fd9d1056-dfcb53b47a6849ce.js:1
a$ @ fd9d1056-dfcb53b47a6849ce.js:1
aV @ fd9d1056-dfcb53b47a6849ce.js:1
a2 @ fd9d1056-dfcb53b47a6849ce.js:1
aV @ fd9d1056-dfcb53b47a6849ce.js:1
a2 @ fd9d1056-dfcb53b47a6849ce.js:1
aV @ fd9d1056-dfcb53b47a6849ce.js:1
a2 @ fd9d1056-dfcb53b47a6849ce.js:1
aV @ fd9d1056-dfcb53b47a6849ce.js:1
a2 @ fd9d1056-dfcb53b47a6849ce.js:1
aV @ fd9d1056-dfcb53b47a6849ce.js:1
a2 @ fd9d1056-dfcb53b47a6849ce.js:1
aV @ fd9d1056-dfcb53b47a6849ce.js:1
a2 @ fd9d1056-dfcb53b47a6849ce.js:1
aV @ fd9d1056-dfcb53b47a6849ce.js:1
a2 @ fd9d1056-dfcb53b47a6849ce.js:1
aV @ fd9d1056-dfcb53b47a6849ce.js:1
a2 @ fd9d1056-dfcb53b47a6849ce.js:1
aV @ fd9d1056-dfcb53b47a6849ce.js:1
a2 @ fd9d1056-dfcb53b47a6849ce.js:1
aV @ fd9d1056-dfcb53b47a6849ce.js:1
(anonymous) @ fd9d1056-dfcb53b47a6849ce.js:1
o7 @ fd9d1056-dfcb53b47a6849ce.js:1
n2 @ fd9d1056-dfcb53b47a6849ce.js:1
(anonymous) @ fd9d1056-dfcb53b47a6849ce.js:1
o7 @ fd9d1056-dfcb53b47a6849ce.js:1
oH @ fd9d1056-dfcb53b47a6849ce.js:1
oj @ fd9d1056-dfcb53b47a6849ce.js:1
M @ 69-9a0f3fb9a2c5697d.js:1

**Comment by ItzCrazyKns** [comment] 2024-09-07 15:33
can you provide the logs from the browser console

**Comment by again2k** [comment] 2024-09-07 16:23
I got the same issue, when click 'Search images' or 'Search videos'

console logs:

`453-547b71eb71b166ae.js:1 
        
        
       POST http://127.0.0.1:3001/api/videos 500 (Internal Server Error)
onClick @ 453-547b71eb71b166ae.js:1
aS @ fd9d1056-dfcb53b47a6849ce.js:1
aN @ fd9d1056-dfcb53b47a6849ce.js:1
(anonymous) @ fd9d1056-dfcb53b47a6849ce.js:1
sw @ fd9d1056-dfcb53b47a6849ce.js:1
sS @ fd9d1056-dfcb53b47a6849ce.js:1
(anonymous) @ fd9d1056-dfcb53b47a6849ce.js:1
oK @ fd9d1056-dfcb53b47a6849ce.js:1
iL @ fd9d1056-dfcb53b47a6849ce.js:1
sN @ fd9d1056-dfcb53b47a6849ce.js:1
uE @ fd9d1056-dfcb53b47a6849ce.js:1
uS @ fd9d1056-dfcb53b47a6849ce.js:1
69-9a0f3fb9a2c5697d.js:1 TypeError: Cannot read properties of undefined (reading 'length')
    at F (453-547b71eb71b166ae.js:1:14343)
    at rk (fd9d1056-dfcb53b47a6849ce.js:1:40395)
    at lI (fd9d1056-dfcb53b47a6849ce.js:1:59202)
    at iB (fd9d1056-dfcb53b47a6849ce.js:1:117301)
    at o4 (fd9d1056-dfcb53b47a6849ce.js:1:94657)
    at fd9d1056-dfcb53b47a6849ce.js:1:94479
    at o3 (fd9d1056-dfcb53b47a6849ce.js:1:94486)
    at oQ (fd9d1056-dfcb53b47a6849ce.js:1:91973)
    at oj (fd9d1056-dfcb53b47a6849ce.js:1:91398)
    at MessagePort.M (69-9a0f3fb9a2c5697d.js:1:80137)
push.945.window.console.error @ 69-9a0f3fb9a2c5697d.js:1
lE @ fd9d1056-dfcb53b47a6849ce.js:1
n.callback @ fd9d1056-dfcb53b47a6849ce.js:1
ng @ fd9d1056-dfcb53b47a6849ce.js:1
ny @ fd9d1056-dfcb53b47a6849ce.js:1
a$ @ fd9d1056-dfcb53b47a6849ce.js:1
aV @ fd9d1056-dfcb53b47a6849ce.js:1
a2 @ fd9d1056-dfcb53b47a6849ce.js:1
aV @ fd9d1056-dfcb53b47a6849ce.js:1
a2 @ fd9d1056-dfcb53b47a6849ce.js:1
aV @ fd9d1056-dfcb53b47a6849ce.js:1
a2 @ fd9d1056-dfcb53b47a6849ce.js:1
aV @ fd9d1056-dfcb53b47a6849ce.js:1
a2 @ fd9d1056-dfcb53b47a6849ce.js:1
aV @ fd9d1056-dfcb53b47a6849ce.js:1
a2 @ fd9d1056-dfcb53b47a6849ce.js:1
aV @ fd9d1056-dfcb53b47a6849ce.js:1
a2 @ fd9d1056-dfcb53b47a6849ce.js:1
aV @ fd9d1056-dfcb53b47a6849ce.js:1
a2 @ fd9d1056-dfcb53b47a6849ce.js:1
aV @ fd9d1056-dfcb53b47a6849ce.js:1
a2 @ fd9d1056-dfcb53b47a6849ce.js:1
aV @ fd9d1056-dfcb53b47a6849ce.js:1
a2 @ fd9d1056-dfcb53b47a6849ce.js:1
aV @ fd9d1056-dfcb53b47a6849ce.js:1
(anonymous) @ fd9d1056-dfcb53b47a6849ce.js:1
o7 @ fd9d1056-dfcb53b47a6849ce.js:1
oH @ fd9d1056-dfcb53b47a6849ce.js:1
oj @ fd9d1056-dfcb53b47a6849ce.js:1
M @ 69-9a0f3fb9a2c5697d.js:1
453-547b71eb71b166ae.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'map')
    at onClick (453-547b71eb71b166ae.js:1:13548)`

**Comment by juancarlosm** [comment] 2024-09-09 09:41
> can you provide the logs from the browser console

I have updated the initial issue with console logs

**Comment by ItzCrazyKns** [comment] 2024-09-10 09:09
I'll try to reproduce

**Comment by ItzCrazyKns** [comment] 2024-09-10 09:37
Turns out it was an issue with `markdown-to-jsx` which is what we use to parse markdown. Please follow this issue for more updates: https://github.com/quantizor/markdown-to-jsx/issues/602

**Comment by ItzCrazyKns** [comment] 2024-11-14 08:05
Fixed in https://github.com/ItzCrazyKns/Perplexica/commit/a1a7470ca6b43cc66677c9119505c0cf901207bf

**Closed by ItzCrazyKns** 2024-11-14 08:05 UTC
Labels: bug
